# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Andrej/VHDL_projects/ip_repo/PIVOT_1.0/src/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrej/VHDL_projects/ip_repo/PIVOT_1.0/src/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Andrej/VHDL_projects/ip_repo/PIVOT_1.0/src/div_gen_0/div_gen_0.xci
# IP: The module: 'div_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Andrej/VHDL_projects/ip_repo/PIVOT_1.0/src/div_gen_0/div_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
