# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/student/Git/psds_projekat_simplex/Simplex/Simplex.srcs/sources_1/bd/simplex/ip/simplex_processing_system7_0_0_1/simplex_processing_system7_0_0.xci
# IP: The module: 'simplex_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Git/psds_projekat_simplex/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_processing_system7_0_0_1/simplex_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simplex_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/student/Git/psds_projekat_simplex/Simplex/Simplex.srcs/sources_1/bd/simplex/ip/simplex_processing_system7_0_0_1/simplex_processing_system7_0_0.xci
# IP: The module: 'simplex_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/student/Git/psds_projekat_simplex/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_processing_system7_0_0_1/simplex_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'simplex_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
