# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.srcs/sources_1/bd/simplex/ip/simplex_axi_smc_0/simplex_axi_smc_0.xci
# IP: The module: 'simplex_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/bd_dcce.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_0/bd_dcce_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_2/bd_dcce_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_3/bd_dcce_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_4/bd_dcce_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_5/bd_dcce_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_6/bd_dcce_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_7/bd_dcce_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_8/bd_dcce_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_9/bd_dcce_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_10/bd_dcce_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_11/bd_dcce_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_12/bd_dcce_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_13/bd_dcce_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_14/bd_dcce_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_15/bd_dcce_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_16/bd_dcce_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_17/bd_dcce_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_18/bd_dcce_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_19/bd_dcce_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_20/bd_dcce_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_21/bd_dcce_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_22/bd_dcce_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_23/bd_dcce_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_24/bd_dcce_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_25/bd_dcce_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_26/bd_dcce_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_27/bd_dcce_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_28/bd_dcce_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_29/bd_dcce_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_2/bd_dcce_arsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_3/bd_dcce_rsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_4/bd_dcce_awsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_5/bd_dcce_wsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_6/bd_dcce_bsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_10/bd_dcce_s00a2s_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_11/bd_dcce_sarn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_12/bd_dcce_srn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_13/bd_dcce_sawn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_14/bd_dcce_swn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_15/bd_dcce_sbn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_16/bd_dcce_m00s2a_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_17/bd_dcce_m00arn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_18/bd_dcce_m00rn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_19/bd_dcce_m00awn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_20/bd_dcce_m00wn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_21/bd_dcce_m00bn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_23/bd_dcce_m01s2a_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_24/bd_dcce_m01arn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_25/bd_dcce_m01rn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_26/bd_dcce_m01awn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_27/bd_dcce_m01wn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_28/bd_dcce_m01bn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simplex_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.srcs/sources_1/bd/simplex/ip/simplex_axi_smc_0/simplex_axi_smc_0.xci
# IP: The module: 'simplex_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/bd_dcce.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_0/bd_dcce_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_2/bd_dcce_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_3/bd_dcce_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_4/bd_dcce_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_5/bd_dcce_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_6/bd_dcce_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_7/bd_dcce_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_8/bd_dcce_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_9/bd_dcce_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_10/bd_dcce_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_11/bd_dcce_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_12/bd_dcce_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_13/bd_dcce_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_14/bd_dcce_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_15/bd_dcce_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_16/bd_dcce_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_17/bd_dcce_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_18/bd_dcce_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_19/bd_dcce_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_20/bd_dcce_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_21/bd_dcce_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_22/bd_dcce_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_23/bd_dcce_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_24/bd_dcce_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_25/bd_dcce_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_26/bd_dcce_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_27/bd_dcce_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_28/bd_dcce_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_29/bd_dcce_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_1/bd_dcce_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_2/bd_dcce_arsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_3/bd_dcce_rsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_4/bd_dcce_awsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_5/bd_dcce_wsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_6/bd_dcce_bsw_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_10/bd_dcce_s00a2s_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_11/bd_dcce_sarn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_12/bd_dcce_srn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_13/bd_dcce_sawn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_14/bd_dcce_swn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_15/bd_dcce_sbn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_16/bd_dcce_m00s2a_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_17/bd_dcce_m00arn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_18/bd_dcce_m00rn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_19/bd_dcce_m00awn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_20/bd_dcce_m00wn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_21/bd_dcce_m00bn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_23/bd_dcce_m01s2a_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_24/bd_dcce_m01arn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_25/bd_dcce_m01rn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_26/bd_dcce_m01awn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_27/bd_dcce_m01wn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/bd_0/ip/ip_28/bd_dcce_m01bn_0_ooc.xdc

# XDC: c:/Users/Andrej/VHDL_projects/Simplex/Simplex.gen/sources_1/bd/simplex/ip/simplex_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'simplex_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
