# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/simplex/simplex.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex || ORIG_REF_NAME==simplex} -quiet] -quiet

# IP: bd/simplex/ip/simplex_processing_system7_0_0_1/simplex_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex_processing_system7_0_0 || ORIG_REF_NAME==simplex_processing_system7_0_0} -quiet] -quiet

# IP: bd/simplex/ip/simplex_axi_bram_ctrl_0_0_1/simplex_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex_axi_bram_ctrl_0_0 || ORIG_REF_NAME==simplex_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/simplex/ip/simplex_PIVOT_0_0/simplex_PIVOT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex_PIVOT_0_0 || ORIG_REF_NAME==simplex_PIVOT_0_0} -quiet] -quiet

# IP: bd/simplex/ip/simplex_axi_smc_0_1/simplex_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex_axi_smc_0 || ORIG_REF_NAME==simplex_axi_smc_0} -quiet] -quiet

# IP: bd/simplex/ip/simplex_rst_ps7_0_100M_0_1/simplex_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==simplex_rst_ps7_0_100M_0 || ORIG_REF_NAME==simplex_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: /home/student/Git/psds_projekat_simplex/Simplex/Simplex.gen/sources_1/bd/simplex/simplex_ooc.xdc
